 /**
 * @description Utility class for constants to be used across classes
 * @author Angelika Galang
 * @since July 3, 2023
 */

public inherited sharing class ams_UTL_Constants {
    //object names

    //spaces and punctuations
    public static final String EMPTY_STRING = '';
    public static final String EMPTY_STRING_1 = ' ';
    public static final String COMMA = ',';

    //operators

    //test values
    
    //numerical
}